# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amadoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=30, null='True'),
        ),
        migrations.AddField(
            model_name='profile',
            name='fname',
            field=models.CharField(max_length=30, null='True'),
        ),
        migrations.AddField(
            model_name='profile',
            name='lname',
            field=models.CharField(max_length=30, null='True'),
        ),
    ]
