# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amadoapp', '0002_auto_20180625_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(choices=[('IN', 'India'), ('US', 'United States'), ('CH', 'China'), ('UK', 'United Kingdom')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ph_number',
            field=models.IntegerField(null='True'),
        ),
        migrations.AddField(
            model_name='profile',
            name='zip_code',
            field=models.IntegerField(null='True'),
        ),
    ]
